# This is a basic workflow that is manually triggered

name: EPG 
on:
 workflow_dispatch:
 schedule:
    - cron: "* * * * *"

jobs:
  epg:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --no-index
      - name: Get EPG Data
        run: python epg.py epg.xml.gz
        env:
          RES_PXY: ${{ secrets.API_KEY }}
          RES_PXY2: ${{ secrets.ACC2 }}
      - name: pull latest
        run: |
          git pull
      - name: Commit updated epg.xml
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated EPG
